server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ph-neutralizer

# Neutralizer Hardware Configuration
neutralizer:
  arduino:
    port: /dev/ttyACM0
    baudrate: 38400
    slave-id: 1
  archive:
    dir: /usr/local/controler/backup

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Logging
logging:
  level:
    bio.altar.phneutralizer: DEBUG
    root: INFO
