server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ph-neutralizer

# Modbus Configuration
modbus:
  connections:
    - name: neutralizer
      host: rtu:///dev/ttyACM0:38400
      timeout: 2000
      parity: none
      stop-bits: 1
      data-bits: 8

# Neutralizer Hardware Configuration
neutralizer:
  connection-name: neutralizer
  slave-id: 1

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Logging
logging:
  level:
    bio.altar.phneutralizer: DEBUG
    root: INFO
  event:
    path: ./logs
    retention-days: 30
